"""initial schema -- PHASE-1 section 6

All six tables land in one migration. Only `listings` is populated in P1; `sessions`,
`decisions`, `memories` and `bookings` are filled by P3, P5, P4 and P8. Creating them
together costs one migration instead of four and keeps the schema readable in one place.

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-07 23:19:11.494775
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('offer_type', sa.String(length=16), nullable=False),
    sa.Column('market_value_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('market_value_currency', sa.String(length=3), nullable=False),
    sa.Column('price_buy_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rental_daily_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=16), nullable=False),
    sa.Column('transmission', sa.String(length=16), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('doors', sa.Integer(), nullable=False),
    sa.Column('insurance_band', sa.Integer(), nullable=False),
    sa.Column('service_interval_km', sa.Integer(), nullable=True),
    sa.Column('timing_mechanism', sa.String(length=8), nullable=False),
    sa.Column('powertrain_archetype', sa.String(length=24), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('insurance_band BETWEEN 1 AND 20', name='ck_listings_insurance_band'),
    sa.CheckConstraint('mileage_km >= 0', name='ck_listings_mileage_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_listings_source_source_id')
    )
    op.create_index('ix_listings_available_from', 'listings', ['available_from'], unique=False)
    op.create_index('ix_listings_brand', 'listings', ['brand'], unique=False)
    op.create_index('ix_listings_category_offer', 'listings', ['category', 'offer_type'], unique=False)
    op.create_index('ix_listings_live', 'listings', ['source'], unique=False, postgresql_where=sa.text('withdrawn_at IS NULL'))
    op.create_index('ix_listings_market_value', 'listings', ['market_value_amount'], unique=False)
    op.create_index('ix_listings_mileage', 'listings', ['mileage_km'], unique=False)
    op.create_index('ix_listings_year', 'listings', ['year'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_user_kind', 'memories', ['user_id', 'kind'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('audit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idempotency_key', name='uq_bookings_idempotency')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_session_turn', 'decisions', ['session_id', 'turn'], unique=False)
    # [SCALE] semantic search. The extension and the column exist now so that enabling
    # pgvector later is a backfill, not a migration against a live listings table.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('listing_vectors',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_vectors')
    op.drop_index('ix_decisions_session_turn', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_memories_user_kind', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_listings_year', table_name='listings')
    op.drop_index('ix_listings_mileage', table_name='listings')
    op.drop_index('ix_listings_market_value', table_name='listings')
    op.drop_index('ix_listings_live', table_name='listings', postgresql_where=sa.text('withdrawn_at IS NULL'))
    op.drop_index('ix_listings_category_offer', table_name='listings')
    op.drop_index('ix_listings_brand', table_name='listings')
    op.drop_index('ix_listings_available_from', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
